--------------------------------------------
-------------INFLUENCERS TABLE--------------
--------------------------------------------

-- 1) Which platform has the highest number of influencers?

DELIMITER $$
CREATE PROCEDURE GetTopPlatformsByInfluencerCount(IN p_limit INT)
BEGIN
    SELECT platform, COUNT(*) AS influencer_count
    FROM Influencers_table
    GROUP BY platform
    ORDER BY influencer_count DESC
    LIMIT p_limit;
END$$
DELIMITER ;
CALL GetTopPlatformsByInfluencerCount(5);

-- 2) Which influencer has participated in the most campaigns?
DELIMITER $$

CREATE PROCEDURE GetTopInfluencersByCampaignCount(IN p_limit INT)
BEGIN
    SELECT i.influencer_id,
           influencer_name,
           platform,
           COUNT(c.campaign_id) AS campaign_type
    FROM Influencers_table i
    LEFT JOIN Campaigns_table c ON c.influencer_id = i.influencer_id
    GROUP BY influencer_id, influencer_name, platform
    ORDER BY campaign_type DESC
    LIMIT p_limit;
END$$
DELIMITER ;
drop procedure GetTopInfluencersByCampaignCount;
CALL GetTopInfluencersByCampaignCount(5);

-- 3) What is the average ROI generated by each influencer?
DELIMITER $$

CREATE PROCEDURE GetTopInfluencersByAvgROI(IN p_limit INT)
BEGIN
    SELECT i.influencer_id,
           influencer_name,
           platform,
           ROUND(AVG(c.roi), 2) AS avg_roi,
           COUNT(c.campaign_id) AS campaign_count
    FROM Influencers_table i
    JOIN Campaigns_table c ON c.influencer_id = i.influencer_id
    WHERE c.roi IS NOT NULL
    GROUP BY i.influencer_id, i.influencer_name, i.platform
    HAVING campaign_count >= 1
    ORDER BY avg_roi DESC
    LIMIT p_limit;
END$$
DELIMITER ;
drop procedure GetTopInfluencersByAvgROI;
CALL GetTopInfluencersByAvgROI(5);


-- 4) How do influencers perform across different platforms?
DELIMITER $$

CREATE PROCEDURE GetPlatformPerformanceByROI(IN p_limit INT)
BEGIN
    SELECT platform,
           ROUND(AVG(c.roi), 2) AS avg_roi,
           COUNT(*) AS campaign_count
    FROM Influencers_table i
    JOIN Campaigns_table c ON c.influencer_id = i.influencer_id
    GROUP BY platform
    ORDER BY avg_roi DESC
    LIMIT p_limit;
END$$
DELIMITER ;
drop PROCEDURE GetPlatformPerformanceByROI;
CALL GetPlatformPerformanceByROI(5);

-- 5) Which influencers deliver the best engagement rates in their campaigns?
DELIMITER $$

CREATE PROCEDURE GetTopInfluencersByEngagement(IN p_limit INT)
BEGIN
    SELECT i.influencer_id,
           influencer_name,
           platform,
           ROUND(AVG(c.engagement_rate), 2) AS avg_engagement_rate,
           COUNT(c.campaign_id) AS campaign_count
    FROM Influencers_table i
    JOIN Campaigns_table c ON c.influencer_id = i.influencer_id
    WHERE c.engagement_rate IS NOT NULL
    GROUP BY i.influencer_id, i.influencer_name, i.platform
    HAVING campaign_count >= 1
    ORDER BY avg_engagement_rate DESC
    LIMIT p_limit;
END$$
DELIMITER ;
drop PROCEDURE GetTopInfluencersByEngagement;
CALL GetTopInfluencersByEngagement(5);
